#!/usr/bin/env bash
set -euo pipefail

# The OpenAPI app-permissions schema omits several valid permissions (e.g.
# actions_variables), so the catalog is the union of it and the GitHub docs
# permission data.
SPEC_URL="https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json"
DOCS_URL="https://raw.githubusercontent.com/github/docs/main/src/github-apps/data"
DOCS_VERSIONS=("fpt-2026-03-10" "ghec-2026-03-10")

spec="$(curl -fsSL "$SPEC_URL")"

entry_count="$(echo "$spec" | jq '.components.schemas["app-permissions"].properties | length')"
if [ "$entry_count" -lt 40 ]; then
	echo "gen-catalog: expected at least 40 permission entries, got $entry_count" >&2
	exit 1
fi

docs=""
for v in "${DOCS_VERSIONS[@]}"; do
	doc="$(curl -fsSL "$DOCS_URL/$v/server-to-server-permissions.json")"
	doc_count="$(echo "$doc" | jq 'length')"
	if [ "$doc_count" -lt 60 ]; then
		echo "gen-catalog: expected at least 60 docs permission entries in $v, got $doc_count" >&2
		exit 1
	fi
	docs+="$doc"
done

entries="$(printf '%s\n%s' "$spec" "$docs" | jq -rs '
	(.[0].components.schemas["app-permissions"].properties
		| map_values(.enum // ["read", "write"])) as $api
	| ([.[1:][] | map_values([.permissions[].access])]) as $docs
	| reduce ([$api] + $docs)[] as $src ({}; reduce ($src | to_entries[]) as $e (.; .[$e.key] += $e.value))
	| to_entries
	| sort_by(.key)
	| .[]
	| .value |= (unique | map(select(. == "read" or . == "write" or . == "admin")) | sort_by({"read": 1, "write": 2, "admin": 3}[.]))
	| select(.value | length > 0)
	| "\t\"" + .key + "\": {" + (.value | map("\"" + . + "\"") | join(", ")) + "},"
')"

cat <<EOF | gofmt
// Code generated by scripts/gen-catalog.sh from the GitHub REST API OpenAPI spec and GitHub docs permission data. DO NOT EDIT.

package perm

var Catalog = map[string][]string{
${entries}
}
EOF
