#!/usr/bin/env bash
set -euo pipefail

SPEC_URL="https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json"

spec="$(curl -fsSL "$SPEC_URL")"

entry_count="$(echo "$spec" | jq '.components.schemas["app-permissions"].properties | length')"
if [ "$entry_count" -lt 40 ]; then
	echo "gen-catalog: expected at least 40 permission entries, got $entry_count" >&2
	exit 1
fi

entries="$(echo "$spec" | jq -r '
	.components.schemas["app-permissions"].properties
	| to_entries
	| sort_by(.key)
	| .[]
	| "\t\"" + .key + "\": {" + ((.value.enum // ["read", "write"]) | map("\"" + . + "\"") | join(", ")) + "},"
')"

cat <<EOF | gofmt
// Code generated by scripts/gen-catalog.sh from the GitHub REST API OpenAPI spec. DO NOT EDIT.

package perm

var Catalog = map[string][]string{
${entries}
}
EOF
